// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0bTj37pRfyI7EGXqr8tM6weH2UvnJzSo',
    appId: '1:746073923297:web:832b5b90ee5b6784dce1a0',
    messagingSenderId: '746073923297',
    projectId: 'aitalkenglish-fc26c',
    authDomain: 'aitalkenglish-fc26c.firebaseapp.com',
    storageBucket: 'aitalkenglish-fc26c.firebasestorage.app',
    measurementId: 'G-TQWF93YVE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApFxDPWiRVvGqtCeuDfmm-O5ml9UqNLMs',
    appId: '1:746073923297:android:c111e0f386cebd93dce1a0',
    messagingSenderId: '746073923297',
    projectId: 'aitalkenglish-fc26c',
    storageBucket: 'aitalkenglish-fc26c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvp-2PjmIRMrO92wiQQSlZXf7g7epj6uc',
    appId: '1:746073923297:ios:390b1e6fe834531bdce1a0',
    messagingSenderId: '746073923297',
    projectId: 'aitalkenglish-fc26c',
    storageBucket: 'aitalkenglish-fc26c.firebasestorage.app',
    iosClientId: '746073923297-4gqt85uv3756qc7a0d3lilpf4359bf07.apps.googleusercontent.com',
    iosBundleId: 'com.example.aitalkCopilot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvp-2PjmIRMrO92wiQQSlZXf7g7epj6uc',
    appId: '1:746073923297:ios:390b1e6fe834531bdce1a0',
    messagingSenderId: '746073923297',
    projectId: 'aitalkenglish-fc26c',
    storageBucket: 'aitalkenglish-fc26c.firebasestorage.app',
    iosClientId: '746073923297-4gqt85uv3756qc7a0d3lilpf4359bf07.apps.googleusercontent.com',
    iosBundleId: 'com.example.aitalkCopilot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0bTj37pRfyI7EGXqr8tM6weH2UvnJzSo',
    appId: '1:746073923297:web:10f39fd9b75f9e11dce1a0',
    messagingSenderId: '746073923297',
    projectId: 'aitalkenglish-fc26c',
    authDomain: 'aitalkenglish-fc26c.firebaseapp.com',
    storageBucket: 'aitalkenglish-fc26c.firebasestorage.app',
    measurementId: 'G-TC67KCR6J7',
  );
}
